### ISSUE TITLE
Offer robots.txt endpoint

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-api#746]
Currently all requests for robots.txt end up with a NumberFormatException in the logs

```
 2023-05-31 12:36:20.497  WARN 1 --- [67c97b7a-71b4-45df-999b-acd63e404e2c] [nio-8010-exec-1] c.f.a.e.GlobalControllerExceptionHandler : Internal server error

 org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "robots.txt"
         at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:133)
         at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
         at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:181)
         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:148)
         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at com.faforever.api.logging.SlowRequestDetectionFilter.doFilter(SlowRequestDetectionFilter.java:35)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
         at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:477)
         at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:338)
         at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:80)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:126)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:128)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
         at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:225)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:238)
         at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:321)
         at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:222)
         at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:135)
         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at com.faforever.api.logging.RequestIdFilter.doFilter(RequestIdFilter.java:55)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
         at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.base/java.lang.Thread.run(Thread.java:833)
 Caused by: java.lang.NumberFormatException: For input string: "robots.txt"
         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
         at java.base/java.lang.Integer.parseInt(Integer.java:668)
         at java.base/java.lang.Integer.valueOf(Integer.java:999)
         at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:203)
         at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115)
         at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:425)
         at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:398)
         at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
         at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
         at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:53)
         at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:729)
         at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:125)
         ... 117 common frames omitted
```

**Comment by Brutus5000** [comment]
As it turns out this is caused by the Traefik redirect from replays.faforever.com
